### ISSUE TITLE
Add Hover on Instagram & Linked Icons

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [Anupkjha2601/food-recipes-website#111]
@Anupkjha2601, Please assign this issue to me as a gssoc'2023 contributor I want to work on this feature.

Feature - on hovering over other social icons the colour shows but for Instagram & LinkedIn icons it is not added
Here in the footer -
![Screenshot 2023-05-22 224513](https://github.com/Anupkjha2601/food-recipes-website/assets/125626654/aa76900e-34e8-4cd6-b993-4809f23cf0b1)

**Comment by wth-amna** [comment]
I would like to work on this issue, kindly assign it to me under GSSOC'23. 
thanks

**Comment by MOHDNEHALKHAN** [comment]
@Ajay4486 , please assign me
