### ISSUE TITLE
Improving and styling the scroll to top arrow.

### ISSUE THREAD

**Issue by SrishtiSonam** [Anupkjha2601/food-recipes-website#127]
<img width="44" alt="image" src="https://github.com/Anupkjha2601/food-recipes-website/assets/113123593/cd2b2867-36f1-47ba-b253-d30bdff35dca">
Improving the styling the scroll to top arrow.
Assign me this issue under gssoc'23.

**Comment by shrashti2004** [comment]
i could improve the styling of scroll to top arrow

**Comment by SrishtiSonam** [comment]
Thank you assigning this task to me.
