### ISSUE TITLE
Add LICENSE to repository

### ISSUE THREAD

**Issue by thrilseekr** [Anupkjha2601/food-recipes-website#131]
I'll Add LICENSE to repository.

**Comment by srivatsavsurya** [comment]
It seems like there is no update in this issue 
I'm here to resolve this!
I'll Add LICENSE to repository.

**Comment by mohit-dhote** [comment]
can you please assign this issue to me, I can do it! as there is no update in this issue.

**Comment by lovelymahor** [comment]
can you please assign this issue to me, I can do it! as there is no update in this issue.
