### ISSUE TITLE
Fixing Icon Alignment as well as hover effect [GSSOC'23]

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Anupkjha2601/food-recipes-website#139]
## Fix Icons

I will be fixing the hover effect and the alignment of the social icons in the our chefs section of the home page.
Footer icon hover effect also.

## Screenshots

![image](https://github.com/Anupkjha2601/food-recipes-website/assets/85278243/a8a10d47-6f82-495e-885b-dc88e4f893d1)

https://github.com/Anupkjha2601/food-recipes-website/assets/85278243/72a7179b-025f-42da-af70-f48e83fea0b0

![image](https://github.com/Anupkjha2601/food-recipes-website/assets/85278243/dac9d391-f3f2-4e81-8d59-28b9d319e969)

Please assign me this issue under GSSOC'23

**Comment by manoranjanonline** [comment]
I want to contribute to this issue. Please assign me this issue under GSSOC'23.

**Comment by srjbisht01** [comment]
Please assign this issue to me. I want to make a hover effect in the two socials icons in the chef's section. I will do it quickly.
under the tag of #gssoc'23 tag

**Comment by Swapnil-Singh-99** [comment]
I was busy in my exams so if @srjbisht01 is not working on this issue then,
@goodchai0 Please assign it to me I will be happy to fix this issue pretty soon.

**Comment by Swapnil-Singh-99** [comment]
Are you working on the issue ?

**Comment by Swapnil-Singh-99** [comment]
@Anupkjha2601 please assign this issue to me under GSSOC'23
