### ISSUE TITLE
Addition of content to website replacing random text of lorem

### ISSUE THREAD

**Issue by Santhoshmani1** [Anupkjha2601/food-recipes-website#147]
## ISSUE

The Food recipe website lacks content to the website & contains only random text of lorem ipsum only. 
## Required 
Text & styling is required in order to make the website more appealing to the website.

**Comment by Akanksha038** [comment]
Hello sir,
There is Lack of good content in this food recipe website. Only random text of lorem ipsum is written. Can you Please assign this issue to me?

**Comment by shradha2001** [comment]
I want to replace the random text with useful contents on the website. Please assign this issue to me.

**Comment by 95ruchika** [comment]
Hello Sir,
Lorem's text is not feasible for customers to be eye-catching enough, so I would like to add such content so customers are interested in the website. Please assign this issue to me.
