### ISSUE TITLE
Improve the UI theme of contact-Us page

### ISSUE THREAD

**Issue by deepeshgupta3257** [Anupkjha2601/food-recipes-website#197]
hi, @Anupkjha2601  
I can create nice UI of contact page 
From This
![image](https://github.com/Anupkjha2601/food-recipes-website/assets/108192513/4705fbc8-efed-4cff-8934-8f031aae9ee6)

To similar like this 
![image](https://github.com/Anupkjha2601/food-recipes-website/assets/108192513/d991e367-344c-4377-a660-4f94182613d2)

So, please assign this issue to me under GSSOC'23

**Comment by manoranjanonline** [comment]
please assign me this , i wants to contribute under GSSOC'23
