### ISSUE TITLE
Adding a code of conduct 

### ISSUE THREAD

**Issue by rohanmittal1163** [Anupkjha2601/food-recipes-website#221]
I am reaching out to kindly request the addition of a Code of Conduct to our project. A Code of Conduct serves as a guiding document that helps establish a respectful and inclusive environment for all participants.
I have taken the liberty of drafting a simplified and concise Code of Conduct that I believe aligns with our project's values and objectives. 
hey @goodchai0 pls assign me with this issue
thank you

**Comment by Visbhavesh** [comment]
hey, I wanted to contribute to this issue under GSsoc'23, can you please assign this issue to me.

**Comment by rohanmittal1163** [comment]
hey @Anupkjha2601 @goodchai0 
pls assign me with this issue
I wnat to contribute in this issue and sure it would not be any regret 
thank you

**Comment by rohanmittal1163** [comment]
hey @Anupkjha2601 @goodchai0
pls assign me with this issue
I wnat to contribute in this issue and sure it would not be any regret
thank you
