### ISSUE TITLE
Email being displayed with Capitals in the newsletter subscribing section

### ISSUE THREAD

**Issue by ch-sohan** [Anupkjha2601/food-recipes-website#229]
hi @goodchai0 . I'm sohan . Emails are often written in small letters. In the newsletter subscribing section of the website the email is  being displayed with capital letters. For example if i give xyz123@gmail.com, it is displaying Xyz123@Gmail.Com. I would like to resolve this issue under **Gssoc23**. Please assign me this task.
![image](https://github.com/Anupkjha2601/food-recipes-website/assets/108716877/580d6a7e-7694-4f98-abff-951278534e9e)

**Comment by goodchai0** [comment]
happy coding @ch-sohan

**Comment by ch-sohan** [comment]
Thank you @goodchai0

**Comment by 0xabdulkhalid** [comment]
Hello @goodchai0, i would like you to assign me to this issue regarding designing Project preview image in best quality

- Here's the issue: #213

**Comment by Visbhavesh** [comment]
hey, I wanted to contribute to this issue under GSsoc'23, can you please assign this issue to me.
