### ISSUE TITLE
Instagram hovering effect not working in footer [GSsoc'23 contributor]

### ISSUE THREAD

**Issue by Yashika-Agrawal** [Anupkjha2601/food-recipes-website#30]
The social media handle , Instagram on hovering is not changing color like other social media handles. 
I would like to work on this issue please assign it to me.

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by Atharva-Nimbalkar** [comment]
Hi @Anupkjha2601, I'm reaching out to express my interest in contributing to the project, specifically regarding the issue "Instagram hovering effect not working in the footer" (#30).
Thank you for taking the time to review my request. I eagerly await your response and the opportunity to make a significant contribution to the project.

Best wishes
Atharva Nimbalkar

**Comment by chiki012** [comment]
Hello, I already worked on a food recipe app, so I'm good to handle this issue. please assign me this issue.
I'm GSSOC'23 contributor.

**Comment by Atharva-Nimbalkar** [comment]
Thank you @Anupkjha2601 for assigning it to me. I did this work and sent the pull request (#183 ). I am waiting for your response.
Regards
Atharva Nimbalkar

**Comment by Yashika-Agrawal** [comment]
Hey @Atharva-Nimbalkar , i have already sent the pull request before , i think it is on first come first serve basis.

**Comment by Atharva-Nimbalkar** [comment]
Hello @Yashika-Agrawal, Ohh u also done it, ok. I think @Anupkjha2601 will review our code then he will take the final decision, so let's wait.
