### ISSUE TITLE
Loading on landing page

### ISSUE THREAD

**Issue by Soumyajit2825** [Anupkjha2601/food-recipes-website#331]
I want to add a loading screen while the landing page is rendering the images the loader will load in the main screen
I want to apply this for this project if needed
@Anupkjha2601 Please let me know if it's important

**Comment by Soumyajit2825** [comment]
Just a query
A new feature is have to be of level-2 under gssoc 23?
If I'm not wrong @Anupkjha2601 @goodchai0 
Just asking tbh 😄

**Comment by goodchai0** [comment]
Yes. Index.html is the main landing page.

**Comment by Soumyajit2825** [comment]
When I'm running it locally there is many differences between the live server and this page https://delightful-beach-00b073d10.1.azurestaticapps.net/

**Comment by Soumyajit2825** [comment]
@goodchai0 @Anupkjha2601 Have you checked my PR???
It's been 5 days now ❔
