### ISSUE TITLE
 Update Chefs' Photos and Gather Real Testimonials for Testimonials Section

### ISSUE THREAD

**Issue by Nishitbaria** [Anupkjha2601/food-recipes-website#342]
Currently, there are Problems in the chefs section and the testimonials section on the website. In the chefs section, all the photos displayed are the same, which does not accurately represent the different chefs working with us. Additionally, the testimonials section contains dummy testimonials instead of real feedback from satisfied customers. To improve the website's credibility and showcase our talented chefs and customer satisfaction, it is necessary to address these issues.

**Expected Behavior:**
1. The chefs section should display relevant and distinct photos of each chef, providing a visual representation of their unique skills and specialties.
2. The testimonials section should feature authentic testimonials from real customers, demonstrating their positive experiences and satisfaction with our services.

**Steps to Reproduce:**
1. Visit the chefs section on the website.
2. Observe that all the photos displayed are identical.
3. Scroll down to the testimonials section.
4. Note that the testimonials provided are dummy placeholders.

**Current Behavior:**
1. In the chefs section, all the photos displayed are the same, providing an inaccurate representation of our talented chefs.
2. The testimonials section contains dummy testimonials, which do not reflect real customer feedback.

**Proposed Solution:**
To resolve these issues, the following steps can be taken:

1. Collect relevant and high-quality photos of each chef .
2. Update the chefs section by replacing the current identical photo with the respective chef's photo.
3. Reach out to our satisfied customers and kindly request their testimonials through a dedicated form or direct communication.
4. Once received, review and select authentic testimonials that highlight the positive experiences of our customers.
5. Update the testimonials section with the real testimonials, providing social proof and enhancing the website's credibility.
6. Periodically review and update the testimonials section to ensure it reflects current and recent customer feedback.

please assign me this issue,I will create a pull request resolving this issue

**Comment by karantec** [comment]
Chef section images chnages and more testimonial be added . Please assign me under this issue.

**Comment by Nishitbaria** [comment]
@karantec I am already working this issue
