### ISSUE TITLE
Remove X direction Scrolling.

### ISSUE THREAD

**Issue by devmusiczz** [Anupkjha2601/food-recipes-website#343]
I want to remove the scrolling feature in horizontal direction (x axis) because scrolling not needed in X direction so that website ui will look more clean.

Please assign this issue under gssoc 23'.

[Food Recipe a hotel Category Flat Bootstrap Responsive Website Template _ Home __ w3layouts.webm](https://github.com/Anupkjha2601/food-recipes-website/assets/114563397/5e82126f-ffc2-4664-a590-806d36d05bde)

**Comment by sakshimaluskar2** [comment]
Hey @Anupkjha2601  I will be able to do this , please assign this issue to me under GSSoC'23.
