### ISSUE TITLE
Food logo image not displayed correctly

### ISSUE THREAD

**Issue by Sanyareeta** [Anupkjha2601/food-recipes-website#344]
The thing is opening this website on edge the food logo image in navigation bar is not displaying correctly and also it is consuming a lot of space.
Here is the pic of how the website is looking due to it.
![header section](https://github.com/Anupkjha2601/food-recipes-website/assets/109012546/b095961c-3858-427f-b7a5-980a8774e621)
Please assign me this issue @Anupkjha2601 under gssoc 2023.

**Comment by Anupkjha2601** [comment]
@Sanyareeta please do it quickly , otherwise i have to correct it .

**Comment by Sanyareeta** [comment]
Sorry the website is displaying image correctly, its my fault I opened it through vs code.
My sincere apology for the mistake @Anupkjha2601
