### ISSUE TITLE
Update readme of the repo

### ISSUE THREAD

**Issue by PriyankaTamhankar01** [Anupkjha2601/food-recipes-website#36]
Hi! I would like to contribute to this issue under the GSSoC'23. 

I would be delighted to take up this issue and work on enhancing the attractiveness of your project to encourage more contributions from the community. My plan is to update the project's README file to make it more appealing and informative for potential contributors. 

By highlighting the project's key features, goals, and providing clear instructions on how to contribute, we can increase engagement and attract more developers.

**Comment by Anupkjha2601** [comment]
great, please work on it .

**Comment by PriyankaTamhankar01** [comment]
Please include the **level** tag and merge my pull request. If you have any suggestions or modifications, kindly inform me.
