### ISSUE TITLE
add a side navbar

### ISSUE THREAD

**Issue by ePSA-eJya** [Anupkjha2601/food-recipes-website#362]
add a side navbar for navigation 
@Anupkjha2601 please assign thisissue to me .i am gssoc23 contributor. @goodchai0

**Comment by ePSA-eJya** [comment]
Thanks would complete in a week

**Comment by aditi-chaurasia** [comment]
Please assign this issue to me .

**Comment by ePSA-eJya** [comment]
I am working on this issue @aditi-chaurasia
