### ISSUE TITLE
Setting website width

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Anupkjha2601/food-recipes-website#365]
I will bee centering the website and adjusting the width of the footer to screen width

# Screenshots
![image](https://github.com/Anupkjha2601/food-recipes-website/assets/85278243/7a0ce1c7-5069-4716-9885-aa8492e15fa0)

Please assign me this issue under GSSOC'23

**Comment by Peacesandy** [comment]
please assign me this issue under gssoc 23
