### ISSUE TITLE
Display to top is not looking good!

### ISSUE THREAD

**Issue by Tapabrata-Goswami** [Anupkjha2601/food-recipes-website#4]
![image](https://github.com/Anupkjha2601/finalproj/assets/89471881/bf5b2b13-a2cb-44a9-81c7-3c0717c658d7)

Can I work on it? To improve the design.
Kindly assign this issue to me.
This issue and PR will be for @GSSOC23.
THANK YOU🤝

**Comment by Anupkjha2601** [comment]
Yes , you can work it is a great idea.

**Comment by Tapabrata-Goswami** [comment]
Kindly assign this issue to me.

**Comment by Tapabrata-Goswami** [comment]
ok thanks
assign me
