### ISSUE TITLE
Adding cursor pointer effect after hovering on the photo in the "Today Specials" section. 

### ISSUE THREAD

**Issue by Prajwal0225** [Anupkjha2601/food-recipes-website#40]
### Description:
**Currently, when hovering over the photo in the "Today Specials" section, there is no visual feedback. To improve the user experience and make it consistent with other interactive elements, we can add a cursor pointer property to the photo when it is being hovered over. This will give users a visual cue that the photo.**

Before⤵️
---
![WhatsApp Image 2023-05-20 at 6 39 30 PM](https://github.com/Anupkjha2601/finalproj/assets/103810119/ccfcd90b-052f-4c2f-984c-4917d07071e1)

After ⤵️
 ---
![WhatsApp Image 2023-05-20 at 6 39 29 PM](https://github.com/Anupkjha2601/finalproj/assets/103810119/6ad83fab-efcc-474a-b69b-a21bf01b5378)
---
**Can you please assign this issue to me? if you think it's important so that I can resolve it?**

**Comment by RahulRana701** [comment]
hi @Anupkjha2601 I would like to work on this issue ............under GSSOC 23 tag
