### ISSUE TITLE
Adding favicon to website

### ISSUE THREAD

**Issue by anuza08** [Anupkjha2601/food-recipes-website#44]
website's **favicon** is missing.
 **Please allow me to work on this issue***

**Comment by alwaystanaya20** [comment]
![favicondemo](https://github.com/Anupkjha2601/finalproj/assets/84630655/f4eae003-d001-4f41-93a8-1baec67aff87)

Hey! I'd love to design a Logo 
Or
add a favicon to the same(if the image is provided)

**Comment by Iamdivyak** [comment]
![image](https://github.com/Anupkjha2601/finalproj/assets/102896170/87c625b8-4483-483b-b33b-8d966671de45)

👆🏻this logo I can add this to the favicon please assign this task to me under gssoc contributor

**Comment by Sreenija03** [comment]
I can add the logo of the website as the favicon.Can you please assign this issue to me under GSSOC 2023

**Comment by anuza08** [comment]
@Anupkjha2601 I'VE MADE PR
