### ISSUE TITLE
The navbar in the gallery page is broken

### ISSUE THREAD

**Issue by PoulavBhowmick03** [Anupkjha2601/food-recipes-website#449]
The navbar in the gallery page is broken. It doesn't hole any similarity to the other pages
I would like to fix this
![image](https://github.com/Anupkjha2601/food-recipes-website/assets/133862694/426a4c33-65cc-403d-ba35-ef9a43895127)

**Comment by Pritipatil07** [comment]
I would like to work on this issue. Please assign me this issue under gssoc'23.
