### ISSUE TITLE
The Navbar in the home page is distorted

### ISSUE THREAD

**Issue by PoulavBhowmick03** [Anupkjha2601/food-recipes-website#490]
The navbar in the home page is currently broken
![image](https://github.com/Anupkjha2601/food-recipes-website/assets/133862694/b89d703f-6bd3-4be4-981e-08c218c37f97)
Please assign this

**Comment by ParthMadhvani2** [comment]
hey, please send this issue to me I have solved the navbar issue on all the pages as I am a GSSoC'23 contributor so please assign this under it. I sent a pull request please accept it.
