### ISSUE TITLE
Change design on Scroll To Top Button

### ISSUE THREAD

**Issue by 5h0ov** [Anupkjha2601/food-recipes-website#501]
I would like to change the design of the scroll to top button in the website to something like this concept:
![scrollbutton](https://github.com/Anupkjha2601/food-recipes-website/assets/83227649/c8c7c2d4-3366-45e2-a7f4-988de6725072)

It would be great to contribute to this repo for GSSoC'23!

**Comment by ratuladhikary21** [comment]
please assign this issue to me under GSSOC ' 23.
I would like to work on it.
Thank you!
