### ISSUE TITLE
[Docs] Fix typo in README.md

### ISSUE THREAD

**Issue by jfmartinz** [Anupkjha2601/food-recipes-website#506]
I have noticed two typos in the README.md file that need to be corrected:

The first typo is in the word "withing," which should actually be "within."
The second typo is in the word "brokel," which should be "broken."

I would like to work on fixing these typos as part of my contribution to GSSOC23.

![image](https://github.com/Anupkjha2601/food-recipes-website/assets/129386460/6c8d5110-610c-4cfb-ad82-c16b31b7fe38)
![image](https://github.com/Anupkjha2601/food-recipes-website/assets/129386460/c4e49d62-f669-434c-833f-6e5d0c680a4e)

**Comment by Jaishree2310** [comment]
@jfmartinz I would like to take this token. Can you please assign it to me?
