### ISSUE TITLE
Remove the unwanted content form the Website

### ISSUE THREAD

**Issue by deepeshmlgupta** [Anupkjha2601/food-recipes-website#508]
<img width="957" alt="image" src="https://github.com/Anupkjha2601/food-recipes-website/assets/108192513/4c142df8-6bda-49cf-b5be-644a68f3b9ad">

assign me this issue so, that I can remove all the unwanted content that has been added to the home page 

So, please assign me this task under GSSOC'23 so that I can start working on this issue to fix the issue in your website

**Comment by ShrutiGossain** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Zack-Dx** [comment]
@deepeshgupta3257 done.
