### ISSUE TITLE
text not align

### ISSUE THREAD

**Issue by RitiChandak** [Anupkjha2601/food-recipes-website#528]
in image slider the text is not align and properly visible
![image](https://github.com/Anupkjha2601/food-recipes-website/assets/96969496/49fa5ff3-3c8b-436b-ab0b-d2b84df7b1c2)

**Comment by Neha626177** [comment]
I want to solve this issue please assign me this issue .
Thank You!

**Comment by RitiChandak** [comment]
@Anupkjha2601 @Zack-Dx please assign me this issue
