### ISSUE TITLE
spacing

### ISSUE THREAD

**Issue by BhartiNagpure** [Anupkjha2601/food-recipes-website#598]
some below sections of website there is need to give spacing to look good .
![Screenshot 2023-07-26 145423](https://github.com/Anupkjha2601/food-recipes-website/assets/104631882/4a65e0ba-c395-48ce-9fe3-17ff31ae452a)

**Comment by mohit-dhote** [comment]
Want to fix this issue, please assign it to me @Anupkjha2601
