### ISSUE TITLE
Fix navbar of Contact Page

### ISSUE THREAD

**Issue by 5h0ov** [Anupkjha2601/food-recipes-website#637]
I would like to fix the broken navbar of the contacts page as shown below:

![image](https://github.com/Anupkjha2601/food-recipes-website/assets/83227649/c2b89db6-4eca-41fe-8713-c86c15948ecb)

**Comment by 5h0ov** [comment]
@Anupkjha2601 sir kindly assign me this issue

**Comment by Rimple-kumari** [comment]
@Anupkjha2601  sir please assign me this issue I want to fix the navigation bar of contact page make it more attractive .
fix it in the center of the page.
