### ISSUE TITLE
Remove horizontal scrollbar on home page and Center the post

### ISSUE THREAD

**Issue by SubhamB2003** [Anupkjha2601/food-recipes-website#656]
@Anupkjha2601 Hey, Can you please assign this issue? to me?
![image](https://github.com/Anupkjha2601/food-recipes-website/assets/94003231/4d03fcbd-d734-4573-b86c-44351560699e)

**Comment by Anupkjha2601** [comment]
@SubhamB2003 already assigned to other contribtor.

**Comment by SubhamB2003** [comment]
> @SubhamB2003 already assigned to other contribtor.

Ok
