### ISSUE TITLE
Replace all dummy text [Gssoc'23]

### ISSUE THREAD

**Issue by ChinatuL** [Anupkjha2601/food-recipes-website#82]
Hello. I noticed that there are dummy texts on various pages of the website. For example, the services page. 

![Screenshot (133)](https://github.com/Anupkjha2601/finalproj/assets/97689140/c8f703cd-b455-48da-8987-20736ccca3e3)

I would like to replace all dummy texts with food-related content. Kindly assign this issue to me as a Gssoc'23 contributor.

**Comment by shwetazade27** [comment]
I would like to work on this issue ( Gssoc'23 ) .
